### ISSUE TITLE
Default display on windows is too big

### ISSUE THREAD

**Issue by arm61** [easyScience/easyReflectometryApp#37]
Reported by a user, when launched on windows on a 1920x1080 screen, the main window is too large for the screen and it is not clear how the size can be reduced.

**Comment by arm61** [comment]
seems to not be an issue any more.

**Comment by arm61** [comment]
Need to test on windows to reproduce, but the user had issues with both the installer and main window being too large for the screen.

**Comment by AndrewSazonov** [comment]
This is strange because the default window size of the application is 1280x828, so it should easily fit into 1920x1080. Furthermore, we have this test on Windows during CI, where easyReflectometry runs on a 1920x1080 screen and the test video is recorded for a portion of the screen corresponding to the size of the application plus a small margin around it. See, e.g.: https://github.com/easyScience/easyReflectometryApp/releases/download/untagged-6a901fb437d6d666b4b7/tutorial_Windows_x86-32_v0.0.2-beta.1_develop.mp4

**Comment by arm61** [comment]
Yeah I found it very strange. It is possible it is a set up issue with the users computer. I will see if they will share screenshots.

**Comment by rozyczko** [comment]
I tested the original release on windows and it looked OK, but then, my monitor resolution is some ungodly value, so I'll retest on the laptop resetting resolution to smaller numbers.

**Comment by rozyczko** [comment]
1920x1080 -> easyReflectometry takes exactly what Andrew mentioned, filling way less than the full screen, as expected.
1440x900 is still comfortable with the window taking most of the space. Again, as expected.

**Comment by arm61** [comment]
Closing as not possible to reproduce
